name: CI  

on:  
  push:  
    branches:   
      - main # Change this to your main branch  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v2  
        
      - name: Setup Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '16' # Specify the version your project uses  

      - name: Install Dependencies  
        run: npm install  

      - name: Build  
        run: npm run build # This assumes you have a build script in your package.json  

      - name: Upload Artifact # Update this to the latest version  
        uses: actions/upload-artifact@v3  
        with:  
          name: vite-build  
          path: dist # Change if your output directory is different  

  deploy:  
    runs-on: ubuntu-latest  
    needs: build  
    
    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v2  

      - name: Download Artifact  
        uses: actions/download-artifact@v3  
        with:  
          name: vite-build  

      # Add your deployment step here  
      # Example for deploying to GitHub Pages  
      - name: Deploy to GitHub Pages  
        uses: peaceiris/actions-gh-pages@v3  
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./dist